steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-docker.pkg.dev/$PROJECT_ID/ichooserx-frontend/ichooserx-frontend:$COMMIT_SHA',
        '--build-arg',
        'NEXT_PUBLIC_ICHOOSERX_BE_BASE_URL=${_NEXT_PUBLIC_ICHOOSERX_BE_BASE_URL}',
        '.'
      ]
availableSecrets:
  secretManager:
    - versionName: "projects/ichooserx/secrets/NEXT_PUBLIC_ICHOOSERX_BE_BASE_URL/versions/latest"
      env: "_NEXT_PUBLIC_ICHOOSERX_BE_BASE_URL"

substitutions:
  _NEXT_PUBLIC_ICHOOSERX_BE_BASE_URL: "https://ichooserx-api-387898904134.us-central1.run.app/api/v1"

images:
  - 'us-docker.pkg.dev/$PROJECT_ID/ichooserx-frontend/ichooserx-frontend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE