steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-docker.pkg.dev/$PROJECT_ID/ichooserx-frontend/ichooserx-frontend:$COMMIT_SHA',
        '--build-arg',
        'NEXT_PUBLIC_ICHOOSERX_BE_BASE_URL',
        '.'
      ]
    envs: ['NEXT_PUBLIC_ICHOOSERX_BE_BASE_URL']
    secretEnv: ['NEXT_PUBLIC_ICHOOSERX_BE_BASE_URL']

images:
  - 'us-docker.pkg.dev/$PROJECT_ID/ichooserx-frontend/ichooserx-frontend:$COMMIT_SHA'

availableSecrets:
  secretManager:
    - versionName: "projects/ichooserx/secrets/NEXT_PUBLIC_ICHOOSERX_BE_BASE_URL/versions/latest"
      env: "NEXT_PUBLIC_ICHOOSERX_BE_BASE_URL"

options:
  logging: CLOUD_LOGGING_ONLY