steps:
  - name: 'gcr.io/cloud-builders/docker'
    secretEnv: ['NEXT_PUBLIC_ICHOOSERX_BE_BASE_URL']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔐 Injected Secret: $NEXT_PUBLIC_ICHOOSERX_BE_BASE_URL"
        docker build \
          --build-arg NEXT_PUBLIC_ICHOOSERX_BE_BASE_URL="$NEXT_PUBLIC_ICHOOSERX_BE_BASE_URL" \
          -t us-docker.pkg.dev/${PROJECT_ID}/ichooserx-frontend/ichooserx-frontend:${COMMIT_SHA} \
          .

images:
  - 'us-docker.pkg.dev/${PROJECT_ID}/ichooserx-frontend/ichooserx-frontend:${COMMIT_SHA}'

availableSecrets:
  secretManager:
    - versionName: "projects/ichooserx/secrets/NEXT_PUBLIC_ICHOOSERX_BE_BASE_URL/versions/latest"
      env: "NEXT_PUBLIC_ICHOOSERX_BE_BASE_URL"

options:
  logging: CLOUD_LOGGING_ONLY